server:
  port: 8081
spring:
  application:
    name: service1
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: ${spring.application.name}
