server:
    port: 8083
spring:
    application:
        name: service3
    sleuth:
        sampler:
            percentage: 1.0
    zipkin:
        base-url: http://localhost:9411/
        service:
            name: ${spring.application.name}
